### ISSUE TITLE
Timeout parameter does not interrupt processing in some occasions

### ISSUE THREAD

**Issue by marekhorst** [CeON/CERMINE#32] opened 2016-10-14 14:50 UTC
There are still cases where timeout feature, thoroughly described in #7, doesn't seem to work.

After upgrading CERMINE to newly released `1.10` version I got IIS metadataextraction workflow failure because `ContentExtractor` stuck for more than 1h while getting document content as NLM.

First thing: we got a regression in CERMINE becase even without timeout feature we were able to pass through `ContentExtractor` all available contents without troubles.

Second thing: after CERMINE reaches this point of processing:
```
1.1 Character extraction: 2.385
1.2 Page segmentation: 4.723
1.3 Reading order resolving: 0.422
1.4 Initial classification: 9.869
2.1 Metadata classification: 0.055
```
even though timeout threshold is exceeded processing is not interrupted hanging whole process.

Decreasing timeout value eventually triggers interruption but this is probably caused by CERMINE not reaching "point of no return".

**Comment by dtkaczyk** [comment] 2016-10-14 14:56
@marekhorst Do you observe these problems in case of a specific file(s), or the entire/large portion of a collection? Is it possible to extract problematic PDFs, so that I can look at their extraction process closely?

**Comment by marekhorst** [comment] 2016-10-14 14:58
It looks like specific files. I've just sent you 3 of them by email.

**Comment by dtkaczyk** [comment] 2016-10-21 11:06
The root cause is fixed by commit https://github.com/CeON/CERMINE/commit/d137bc893e9aeae99266d45ca48030d85b1ac88d

**Closed by dtkaczyk** 2016-10-21 11:06 UTC
